apiVersion: v1
kind: Secret
metadata:
  name: cnpg-superuser
  namespace: harbr-system
type: Opaque
stringData:
  username: cnpg_superuser
  password: changeme
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: user-db-template
  namespace: harbr-system
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 5Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cnpg-superuser
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1.0"
      memory: 1Gi
